contracts/reflect/.cargo/config
contracts/reflect/examples/schema.rs
contracts/reflect/schema/execute_msg.json
contracts/reflect/schema/instantiate_msg.json
contracts/reflect/schema/query_msg.json

Fixes error message about missing schema in `make build` log.

Chore: add schema to reflect contract

---

contracts/ibc_transfer/README.md

Related to https://github.com/neutron-org/neutron/pull/73

Chore: remove outdated instruction in README

---

packages/neutron-sdk/schema/interchain_queries.json
packages/neutron-sdk/src/bindings/query.rs
packages/neutron-sdk/src/lib.rs
packages/neutron-sdk/src/query/mod.rs
packages/neutron-sdk/src/query/total_burned_neutrons.rs

Merge with https://github.com/neutron-org/neutron/pull/117 and https://github.com/neutron-org/neutron-integration-tests/pull/57

feat: wasmbindings for TotalBurnedNeutronsAmount #NTRN-300

---

packages/neutron-sdk/src/proto_types/transfer.rs
proto/transfer/v1/transfer.proto

there are 5 PRs related to this task
1) [ICQ relayer](https://github.com/neutron-org/neutron-query-relayer/pull/72)
2) [neutron](https://github.com/neutron-org/neutron/pull/126)
3)  [integration tests](https://github.com/neutron-org/neutron-integration-tests/pull/67)
4) [dev contracts](https://github.com/neutron-org/neutron-dev-contracts/pull/5)
5) [neutron SDK](https://github.com/neutron-org/neutron-sdk/pull/76)
[TEST ACTIONS RUN](https://github.com/neutron-org/neutron-tests/actions/runs/3948296511)

rm interchainadapter NTRN-299

---

contracts/neutron_interchain_txs/src/contract.rs
packages/neutron-sdk/schema/interchain_queries.json
packages/neutron-sdk/schema/neutron_msg.json
packages/neutron-sdk/src/bindings/query.rs
packages/neutron-sdk/src/query/min_ibc_fee.rs
packages/neutron-sdk/src/query/minimum_ibc_fee.rs
packages/neutron-sdk/src/query/mod.rs

Part of https://p2pvalidator.atlassian.net/browse/NTRN-386
Merge with:
- https://github.com/neutron-org/neutron-dev-contracts/pull/11
- https://github.com/neutron-org/neutron/pull/164

feat: query minimum IBC fee #NTRN-386

---

packages/neutron-sdk/src/bindings/msg.rs

[TASK](https://p2pvalidator.atlassian.net/browse/NTRN-387)
[TEST RUN](https://github.com/neutron-org/neutron-tests/actions/runs/4448950096/jobs/7827172874)
Here is implementation of the bindings for the rest types of proposals we're gonna support

NTRN-387 add more wasmbindings

---

contracts/neutron_interchain_txs/schema/sudo_msg.json
packages/neutron-sdk/schema/neutron_msg.json
packages/neutron-sdk/src/bindings/msg.rs

Task: https://p2pvalidator.atlassian.net/browse/NTRN-413
Adds AddSchedule, RemoveSchedule to NeutronMsg enum

feat: cron #ntrn-413

---

contracts/ibc_transfer/src/contract.rs
contracts/neutron_interchain_txs/schema/sudo_msg.json
packages/neutron-sdk/schema/neutron_msg.json
packages/neutron-sdk/src/bindings/msg.rs

added memo for Neutron IbcTransfer message

feat: add memo #ntrn-433

---

packages/neutron-sdk/schema/neutron_msg.json
packages/neutron-sdk/schema/neutron_query.json
packages/neutron-sdk/src/bindings/msg.rs
packages/neutron-sdk/src/bindings/query.rs
packages/neutron-sdk/src/query/mod.rs
packages/neutron-sdk/src/query/token_factory.rs

Foundation for:
- https://github.com/neutron-org/neutron-dev-contracts/pull/16
- https://github.com/neutron-org/neutron-integration-tests/pull/147
Expected merge flow:
1. we review and merge this particular PR
2. we release neutron-sdk v0.5.0
3. I target PR in neutron-dev-contracts to use neutron-sdk v0.5.0
4. we review and merge other two PRs, which both depend on this PR (which will have already been merged in step 1, at this point)
[[Jira task](https://p2pvalidator.atlassian.net/browse/NTRN-431)] [[Recent test run](https://github.com/neutron-org/neutron-tests/actions/runs/4831402575)]

TokenFactory bindings #NTRN-431

---

contracts/ibc_transfer/README.md
contracts/neutron_interchain_queries/README.md
contracts/neutron_interchain_txs/README.md

Change README.md hermes version to `cargo install --git https://github.com/neutron-org/hermes --rev 7defaf0 ibc-relayer-cli --bin hermes --locked`

Change README.md hermes version

---

contracts/ibc_transfer/README.md
contracts/neutron_interchain_queries/README.md
contracts/neutron_interchain_txs/README.md
packages/neutron-sdk/schema/neutron_msg.json

How to test and review:
1. read and review docs in https://github.com/neutron-org/neutron-docs/pull/87
2. run bash tests using updated instructions in https://github.com/neutron-org/neutron-sdk/pull/95
Merge with:
- https://github.com/neutron-org/neutron/pull/257
- https://github.com/neutron-org/neutron-docs/pull/87

feat: bump hermes to v1.4.1

---

scripts/test_icq_wasm_juno_testnet/config.toml

part of documentation update https://hadronlabs.atlassian.net/browse/NTRN-1

chore: update hermes config for 1.6 version #ntrn-1

---

packages/neutron-sdk/schema/neutron_msg.json
packages/neutron-sdk/schema/neutron_query.json
packages/neutron-sdk/src/bindings/msg.rs
packages/neutron-sdk/src/bindings/query.rs
packages/neutron-sdk/src/bindings/types.rs

https://hadronlabs.atlassian.net/browse/NTRN-84

feat: add ResubmitSchedule neutron msg #ntrn-84

---

packages/neutron-sdk/schema/neutron_msg.json
packages/neutron-sdk/schema/neutron_query.json
packages/neutron-sdk/src/bindings/msg.rs
packages/neutron-sdk/src/bindings/query.rs
packages/neutron-sdk/src/query/token_factory.rs

[Task
](https://hadronlabs.atlassian.net/browse/NTRN-93)
- [Neutron PR](https://github.com/neutron-org/neutron/pull/307)
- [Intergration tests ](https://github.com/neutron-org/neutron-integration-tests/pull/200)
- [Neutron SDK](https://github.com/neutron-org/neutron-sdk/pull/110)
- [Dev contracts](https://github.com/neutron-org/neutron-dev-contracts/pull/26)

Update our tokenfactory to the latest version NTRN-93

---

Cargo.toml
README.md
build_release.sh
contracts/ibc_transfer/Cargo.toml
contracts/neutron_interchain_queries/Cargo.toml
contracts/neutron_interchain_queries/src/contract.rs
contracts/neutron_interchain_queries/src/testing/tests.rs
contracts/neutron_interchain_txs/Cargo.toml
contracts/neutron_interchain_txs/src/contract.rs
packages/neutron-sdk/Cargo.toml
packages/neutron-sdk/src/errors/error.rs
packages/neutron-sdk/src/interchain_queries/v045/testing.rs
packages/neutron-sdk/src/interchain_queries/v045/types.rs
packages/neutron-sdk/src/interchain_txs/helpers.rs
rust-toolchain.toml
scripts/test_ibc_transfer.sh
scripts/test_icq_wasm_juno_testnet/test_wasm_query.sh
scripts/test_interchain_txs.sh
scripts/test_kv_query.sh
scripts/test_tx_query.sh
thirdparty/protoc-image/Dockerfile

- bump workspace_optimizer to v0.14.0
- bump Rust dependencies and organize them into workspace
- set release profile at workspace Cargo.toml
- bump Rust toolchain to v1.71.0
- prepare shell scripts for sdk v47: use broadcast mode sync

feat: prepare for release v0.7.0

---

packages/neutron-sdk/src/bindings/msg.rs

[TASK](https://hadronlabs.atlassian.net/browse/NTRN-135)

ice creation fee is optional NTRN-135

---

.github/workflows/tests.yml
Cargo.toml
Makefile
README.md
build_release.sh
contracts/neutron_interchain_queries/schema/execute_msg.json
contracts/neutron_interchain_queries/schema/query_msg.json
contracts/neutron_interchain_queries/src/contract.rs
contracts/neutron_interchain_queries/src/msg.rs
contracts/neutron_interchain_txs/schema/query_msg.json
contracts/neutron_interchain_txs/src/contract.rs
contracts/neutron_interchain_txs/src/msg.rs
packages/neutron-sdk/src/interchain_queries/v045/helpers.rs
packages/neutron-sdk/src/interchain_queries/v045/mod.rs
packages/neutron-sdk/src/interchain_queries/v045/queries.rs
packages/neutron-sdk/src/interchain_queries/v045/register_queries.rs
packages/neutron-sdk/src/interchain_queries/v045/testing.rs
packages/neutron-sdk/src/interchain_queries/v045/types.rs
packages/neutron-sdk/src/stargate/aux.rs
rust-toolchain.toml
scripts/test_interchain_txs.sh

Side changes:
- fix `make compile` caching
- bump rust-optimizer from v0.14.0 to v0.15.0
- bump Rust from v1.71.0 to v1.73.0
- fix entry points in ictx contract
- improve doc comments in ictx contract
- fix ictx integration test
- add `make doc` target
- fix `make doc` warnings

feat: unbonding delegations query

---

packages/neutron-sdk/src/stargate/dex/types.rs

**Related PRs:**
* https://github.com/neutron-org/neutron/pull/511
* https://github.com/neutron-org/neutron-dev-contracts/pull/49

pool_metadata -> Pool_metadata

---

packages/neutron-sdk/src/bindings/marketmap/mod.rs
packages/neutron-sdk/src/bindings/marketmap/query.rs
packages/neutron-sdk/src/bindings/marketmap/types.rs
packages/neutron-sdk/src/bindings/mod.rs
packages/neutron-sdk/src/bindings/oracle/mod.rs
packages/neutron-sdk/src/bindings/oracle/query.rs
packages/neutron-sdk/src/bindings/oracle/types.rs
packages/neutron-sdk/src/bindings/query.rs

Bindings for neutron. Slinky-related
Oracle:
- GetPrice
- GetAllCurrencyPairs
Marketmap:
- Params
- MarketMap
- LastUpdated
Main PR:
https://github.com/neutron-org/neutron/pull/508

NTRN-260 slinky bindings (market map & oracle)

---

Cargo.toml

Related PRs:
* https://github.com/neutron-org/neutron-std/pull/2
* https://github.com/neutron-org/neutron-dev-contracts/pull/72
* https://github.com/neutron-org/neutron-sdk/pull/167
* https://github.com/neutron-org/neutron-integration-tests/pull/366

Feat: respect gogoproto nullable
